OpenAPITools server enhancement
tjquinno/openapi-generator pull request #17
Opened 2022-05-02 11:01 UTC by tvallin

Solves https://github.com/oracle/helidon/issues/4125

Note : There is an option to generate source code only : `--additional-properties generatePom=false`

Signed-off-by: tvallin <thibault.vallin@oracle.com>

2022-05-02 14:16 UTC, tjquinno requested changes
A few comments. There might be a few more coming.

2022-05-02 14:16 UTC, tjquinno commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
> +            supportingFiles = supportingFiles.stream().filter(file -> !file.getTemplateFile().contains("RestApplication.mustache")).collect(Collectors.toList());
Can you remind me why we don't want to generate `RestApplication.java` in the Helidon case?

Also, if we really do need to exclude that file, the Java code would be clearer if we did not add it in the first place near line 180.

2022-05-02 14:16 UTC, tjquinno commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
> +            super.setSourceFolder("src/main/java");
Why is this needed? Wouldn't this override a user setting to generate files into, for example, `generated-sources`?

2022-05-03 08:55 UTC, tvallin commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
> +            super.setSourceFolder("src/main/java");
It is needed because source folder is set to `src/gen/java` by default.

From what I could observe, the `target/generated-sources/openapitools` path is defined by `output` property. The relative path from this output directory and the package folders is defined by `sourceFolder` property. Am I correct or did I miss something ?

Nevertheless I made the changes to have `src/main/java` by default without overridden user's sourceFolder from additional-property in latest commit.

2022-05-19 16:31 UTC, tvallin commented
See https://github.com/tjquinno/openapi-generator/pull/20

2022-05-19 16:31 UTC, closed without merging