[Server MP] REST API files only + class/interface implementation
tjquinno/openapi-generator pull request #50
Opened 2022-08-30 14:30 UTC by tvallin

Signed-off-by: tvallin <thibault.vallin@oracle.com>

2022-09-01 19:26 UTC, spericas commented
Didn't you find calling `processSupportingFiles(modifiable, unmodifiable)` useful?

2022-09-02 07:49 UTC, aserkes requested changes

2022-09-02 07:49 UTC, aserkes commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaHelidonServerCodegen.java
> +            apiTemplateFiles.put("api_impl.mustache", ".java");
if you change it to 
```
apiTemplateFiles.put("api_impl.mustache", "Impl.java");
```
you will not need to override `public String apiFilename(String templateName, String tag)`

2022-09-02 07:49 UTC, aserkes commented on modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaHelidonServerCodegen.java
> +    private boolean apiFilesOnly = false;
you can use `fullProject`

2022-09-05 08:53 UTC, aserkes approved these changes

2022-09-06 20:32 UTC, tjquinno approved these changes

2022-09-07 15:22 UTC, barchetta commented
See https://github.com/oracle/helidon/issues/4708

2022-09-07 15:34 UTC, merged